//! Corpus artifact loading end-to-end (#23 → #16/#17): the shipped
//! fixtures (generated by the corpus crate's real emitter) roundtrip into
//! compose's loaders, and the with/without-artifact contract holds —
//! hand-seeded output is untouched without an artifact, changed but valid
//! with one.

use kontinuum_compose::arrangement::{GenParams, Kind};
use kontinuum_compose::groove::GrooveBank;
use kontinuum_compose::structure::StructureParams;
use kontinuum_compose::generate_session;
use kontinuum_ir::validate_session;

const GROOVE_FIXTURE: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/groove-templates-minimal-techno.json"));
const ARRANGEMENT_FIXTURE: &str =
    include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/arrangement-params-minimal-techno.json"));

#[test]
fn groove_fixture_roundtrips_into_a_bank() {
    let bank = GrooveBank::load_json(GROOVE_FIXTURE).expect("emitter-shaped fixture parses");
    assert_eq!(bank.subgenre, "minimal-techno");
    assert_eq!(bank.corpus_size, 5);
    assert!(!bank.is_empty());
    // Selected templates apply through the shared timing path, deterministically.
    let mut rng = kontinuum_clock::stream(1, 1, 1);
    let g = bank.pick(None, 0.7, &mut rng).expect("fixture has templates");
    let steps = || {
        [0, 480, 960, 1440]
            .iter()
            .map(|&position| kontinuum_ir::schema::Step {
                position,
                velocity: 0.8,
                probability: 1.0,
                microtiming_ticks: 0,
                ratchet: 1,
                pitch: None,
                gate: None,
                accent: false,
            })
            .collect::<Vec<_>>()
    };
    let (mut a, mut b) = (steps(), steps());
    g.apply(&mut a, &mut kontinuum_clock::stream(1, 1, 2));
    g.apply(&mut b, &mut kontinuum_clock::stream(1, 1, 2));
    assert_eq!(a, b, "corpus groove application is deterministic");
}

#[test]
fn arrangement_fixture_roundtrips_into_structure() {
    let s = StructureParams::load_json(ARRANGEMENT_FIXTURE).expect("emitter-shaped fixture parses");
    assert_eq!(s.subgenre, "minimal-techno");
    assert_eq!(s.corpus_size, 5);
    assert!(!s.is_empty());
    // Fixture devs are 16/24/32-bar sections with median 24.
    assert_eq!(s.median_bars(Kind::Dev), Some(24));
    assert_eq!(s.median_bars(Kind::Breakdown), Some(8));
    assert!(s.dev_energy(0, 3).is_some());
}

/// An artifact whose labels map to nothing must be behaviorally identical
/// to no artifact at all.
#[test]
fn session_without_artifact_is_bit_identical_to_hand_seeded() {
    let mut foreign = GenParams { seed: 31, ..GenParams::default() };
    foreign.structure = Some(foreign_structure());
    foreign.groove_bank = Some(empty_bank());
    let plain = generate_session(&GenParams { seed: 31, ..GenParams::default() });
    let fallback = generate_session(&foreign);
    assert_eq!(
        serde_json::to_string(&plain).unwrap(),
        serde_json::to_string(&fallback).unwrap(),
        "unusable artifacts must not move a hair"
    );
}

#[test]
fn session_with_artifacts_is_deterministic_valid_and_changed() {
    let with = GenParams {
        seed: 31,
        structure: StructureParams::load_json(ARRANGEMENT_FIXTURE).ok(),
        groove_bank: GrooveBank::load_json(GROOVE_FIXTURE).ok(),
        ..GenParams::default()
    };
    let a = generate_session(&with);
    let b = generate_session(&with);
    assert_eq!(
        serde_json::to_string(&a).unwrap(),
        serde_json::to_string(&b).unwrap(),
        "artifact-fed generation is deterministic"
    );
    validate_session(&a).expect("artifact-fed session validates");
    let without = generate_session(&GenParams { seed: 31, ..GenParams::default() });
    assert_ne!(
        serde_json::to_string(&a).unwrap(),
        serde_json::to_string(&without).unwrap(),
        "artifacts must change the plan"
    );
}

fn foreign_structure() -> StructureParams {
    let json = r#"{
        "artifact_version": 1,
        "corpus_size": 2,
        "subgenre": "elsewhere",
        "section_lengths": {
            "vox_section": { "mean_bars": 16.0, "std_bars": 2.0, "p10_bars": 12.0, "p50_bars": 16.0, "p90_bars": 20.0 }
        },
        "transition_matrix": {},
        "transition_type_tables": {},
        "energy_arcs": []
    }"#;
    StructureParams::load_json(json).expect("parses")
}

fn empty_bank() -> GrooveBank {
    let json = r#"{
        "artifact_version": 1,
        "corpus_size": 0,
        "subgenre": "elsewhere",
        "templates": []
    }"#;
    GrooveBank::load_json(json).expect("parses")
}
